{% set name = "stestr" %}
{% set version = "4.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/stestr-{{ version }}.tar.gz
  sha256: 45ec639f2d1cc372e3630613b93f37cf29d3dfe69d49d4f3f9408d37b11bc29c

build:
  entry_points:
    - stestr=stestr.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - flit_core >=3.12,<4
  run:
    - cliff >=2.8.0
    - fixtures >=3.0.0
    - python >={{ python_min }}
    - python-subunit >=1.4.0
    - pyyaml >=3.10.0
    - testtools >=2.2.0
    - voluptuous >=0.8.9
    - tomlkit >=0.11.6

test:
  imports:
    - stestr
  commands:
    - pip check
    - stestr -h
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://stestr.readthedocs.io/en/latest/
  summary: A parallel Python test runner built around subunit
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/mtreinish/stestr

extra:
  recipe-maintainers:
    - BastianZim
