{% set name = "stestr" %}
{% set version = "4.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/stestr-{{ version }}.tar.gz
  sha256: b60495225fa783476252572adda29d33ae3706f95fc32564f78fb4e7c9e5df20

build:
  entry_points:
    - stestr=stestr.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pbr >=2.0.0
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - extras >=1.0.0
    - tomlkit >=0.11.6
    - cliff >=2.8.0
    - fixtures >=3.0.0
    - future
    - pbr !=2.1.0,!=4.0.0,!=4.0.1,!=4.0.2,!=4.0.3,>=2.0.0
    - python >={{ python_min }}
    - python-subunit >=1.4.0
    - pyyaml >=3.10.0
    - testtools >=2.2.0
    - voluptuous >=0.8.9
  run_constrained:
    - subunit2sql >=1.8.0

test:
  imports:
    - stestr
  commands:
    - pip check
    - stestr -h
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://stestr.readthedocs.io/en/latest/
  summary: A parallel Python test runner built around subunit
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/mtreinish/stestr

extra:
  recipe-maintainers:
    - BastianZim
