{% set name = "stestr" %}
{% set version = "4.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/stestr-{{ version }}.tar.gz
  sha256: 5f61c369eece63c292d13599e12aa158af7685990643f24dd6fa7fabfe34e98a

build:
  entry_points:
    - stestr=stestr.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pbr >=2.0.0
    - pip
    - python >=3.6
  run:
    - extras >=1.0.0
    - tomlkit >=0.11.6
    - cliff >=2.8.0
    - fixtures >=3.0.0
    - future
    - pbr !=2.1.0,!=4.0.0,!=4.0.1,!=4.0.2,!=4.0.3,>=2.0.0
    - python >=3.6
    - python-subunit >=1.4.0
    - pyyaml >=3.10.0
    - testtools >=2.2.0
    - voluptuous >=0.8.9
  run_constrained:
    - subunit2sql >=1.8.0

test:
  imports:
    - stestr
  commands:
    - pip check
    - stestr -h
  requires:
    - pip

about:
  home: http://stestr.readthedocs.io/en/latest/
  summary: A parallel Python test runner built around subunit
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/mtreinish/stestr

extra:
  recipe-maintainers:
    - BastianZim
